# -*- coding: utf-8 -*-
"""Oasis Task -2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azaPXZx86Y0R1VF2uUswElCq1uQdJmjn

# Name - Anurag Mishra

# Task 2
# UNEMPLOYMENT ANALYSIS WITH PYTHON

Unemployment is measured by the unemployment rate which is the number of people
who are unemployed as a percentage of the total labour force. We have seen a sharp
increase in the unemployment rate during Covid-19, so analyzing the unemployment rate
can be a good data science project.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/Unemployment in India.csv')
data

data.head()

data.info()

"""Converting Date into int format"""

data[' Date']=pd.to_datetime(data[' Date'])
data.describe()

print(data.columns)

data.isnull().sum()

data[' Estimated Employed'] = pd.to_numeric(data[' Estimated Employed'], errors='coerce')

"""# Data Visualization
1.Using Histogram


---


Estimated Employed Rate in India







"""

plt.figure(figsize=(12,12))
plt.title('Indian Employed States')
sns.histplot(x=' Estimated Employed' ,hue='Region',data=data)
plt.grid()
plt.show()

"""2.Using Barplot




*   Estimated Unemployment Rate Of various States of India













"""

plt.figure(figsize=(10, 6))
sns.barplot(x='Region', y=' Estimated Unemployment Rate (%)', data=data, palette='RdYlGn')
plt.title('Unemployment Rate in Indian Regions')
plt.xlabel('Region')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.show()

"""# Data Processing


---
Finding out the Most Unemployed State in India and its Value

"""

most_unemployed_state = data.loc[data[' Estimated Unemployment Rate (%)'].idxmax()]['Region']
highest_unemployment_rate = data[' Estimated Unemployment Rate (%)'].max()

print("State with the highest unemployment rate:", most_unemployed_state)
print("Highest Unemployment Rate:", highest_unemployment_rate)

